### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Taybou**

### CODE REVIEW

**Review by youknowriad — CHANGES_REQUESTED** [review]
Thanks for this addition @Taybou. Would you mind adding a LICENSE file to your repository to match our guidelines. 

I'll be happy to merge this, once done!

**Comment by Taybou** [comment]
All right, done

**Review by youknowriad — APPROVED** [review]

**Comment by youknowriad** [comment]
Awesome thank you @Taybou

**Comment by Taybou** [comment]
Thank you @youknowriad

**Pull request merged**
